site_name: Gemforce Documentation
site_description: Documentation for the Gemforce blockchain platform
site_author: Gemforce Team

# Navigation
nav:
  - Home: index.md
  - Developer Setup Guide: developer-setup-guide.md
  - System Architecture: system-architecture/gemforce-system-architecture.md
  - Smart Contracts:
    - Overview: smart-contracts/index.md
    - Diamond Contract: smart-contracts/diamond.md
    - Diamond Factory: smart-contracts/diamond-factory.md
    - Identity Factory: smart-contracts/identity-factory.md
    - Facets:
      - Marketplace Facet: smart-contracts/facets/marketplace-facet.md
      - Trade Deal Management Facet: smart-contracts/facets/trade-deal-management-facet.md
      - Carbon Credit Facet: smart-contracts/facets/carbon-credit-facet.md
      - Identity Registry Facet: smart-contracts/facets/identity-registry-facet.md
      - Trusted Issuers Registry Facet: smart-contracts/facets/trusted-issuers-registry-facet.md
      - Fee Distributor Facet: smart-contracts/facets/fee-distributor-facet.md
      - Gemforce Minter Facet: smart-contracts/facets/gemforce-minter-facet.md
      - Multi Sale Facet: smart-contracts/facets/multi-sale-facet.md
      - SVG Templates Facet: smart-contracts/facets/svg-templates-facet.md
      - Trade Deal Admin Facet: smart-contracts/facets/trade-deal-admin-facet.md
      - Trade Deal Operations Facet: smart-contracts/facets/trade-deal-operations-facet.md
      - Collateral Token Factory Facet: smart-contracts/facets/collateral-token-factory-facet.md
      - Diamond Cut Facet: smart-contracts/facets/diamond-cut-facet.md
      - Diamond Loupe Facet: smart-contracts/facets/diamond-loupe-facet.md
      - Ownership Facet: smart-contracts/facets/ownership-facet.md
    - Interfaces:
      - IDiamond: smart-contracts/interfaces/idiamond.md
      - IMarketplace: smart-contracts/interfaces/imarketplace.md
      - ITradeDeal: smart-contracts/interfaces/itradedeal.md
      - ICarbonCredit: smart-contracts/interfaces/icarbon-credit.md
      - IERC1155Mint: smart-contracts/interfaces/ierc1155-mint.md
      - IERC734: smart-contracts/interfaces/ierc734.md
      - IERC735: smart-contracts/interfaces/ierc735.md
      - IERC721A: smart-contracts/interfaces/ierc721a.md
      - IDiamondFactory: smart-contracts/interfaces/idiamond-factory.md
      - IIdentity: smart-contracts/interfaces/iidentity.md
      - IMultiSale: smart-contracts/interfaces/imultisale.md
      - IFeeDistributor: smart-contracts/interfaces/ifee-distributor.md
      - IGemforceMinterFacet: smart-contracts/interfaces/igemforce-minter-facet.md
      - IIdentityRegistry: smart-contracts/interfaces/iidentity-registry.md
      - TRUSTEDIssuersRegistry: smart-contracts/interfaces/itrusted-issuers-registry.md
      - ISVG: smart-contracts/interfaces/isvg.md
      - IAttribute: smart-contracts/interfaces/iattribute.md
      - IVariablePrice: smart-contracts/interfaces/ivariable-price.md
    - Libraries:
      - Carbon Credit Lib: smart-contracts/libraries/carbon-credit-lib.md
      - Trade Deal Lib: smart-contracts/libraries/trade-deal-lib.md
      - Multi Sale Lib: smart-contracts/libraries/multi-sale-lib.md
      - Diamond Factory Lib: smart-contracts/libraries/diamond-factory-lib.md
      - SVG Templates Lib: smart-contracts/libraries/svg-templates-lib.md
      - Attribute Lib: smart-contracts/libraries/attribute-lib.md
      - Variable Price Lib: smart-contracts/libraries/variable-price-lib.md
      - Merkle Prover: smart-contracts/libraries/merkle-prover.md
      - Fee Distributor Lib: smart-contracts/libraries/fee-distributor-lib.md
      - LibDiamond: smart-contracts/libraries/lib-diamond.md
      - DiamondLib: smart-contracts/libraries/diamond-lib.md
      - ERC721A Lib: smart-contracts/libraries/erc721a-lib.md
      - ERC721A Enumeration Lib: smart-contracts/libraries/erc721a-enumeration-lib.md
      - Strings Lib: smart-contracts/libraries/strings-lib.md
      - Trusted Issuer Lib: smart-contracts/libraries/trusted-issuer-lib.md
      - Set Libraries: smart-contracts/libraries/set-libraries.md
  - SDK & Libraries:
    - Blockchain Utilities: sdk-libraries/blockchain.md
    - Diamond Utilities: sdk-libraries/diamond.md
    - Contract Utilities: sdk-libraries/contract.md
    - Deployment Utilities: sdk-libraries/deploy.md
    - Validation Utilities: sdk-libraries/validation-utils.md
    - NFT Sale Utilities: sdk-libraries/nft-sale-utils.md
    - Webhooks Utilities: sdk-libraries/webhooks.md
    - Metadata Library: smart-contracts/libraries/metadata-lib.md
  - Cloud Functions:
    - Overview: cloud-functions/index.md
    - Authentication Functions: cloud-functions/authentication.md
    - Auth Functions: cloud-functions/auth-functions.md
    - Blockchain Functions: cloud-functions/blockchain.md
    - Bridge Functions: cloud-functions/bridge.md
    - Contract Functions: cloud-functions/contracts.md
    - Deploy Functions: cloud-functions/deploy.md
    - DFNS Functions: cloud-functions/dfns.md
    - Project Functions: cloud-functions/project.md
    - Trade Deal Functions: cloud-functions/trade-deal.md
  - API Documentation:
    - Full API Reference: api-documentation/gemforce-api-documentation.md
    - Quick Reference: api-documentation/gemforce-api-quick-reference.md
  - External Services: gemforce-external-services.md
  - System Architecture: gemforce-system-architecture.md
  - Operations Tasks:
    - Diamond Tasks: cloud-functions/tasks/diamond.md
    - Identity Tasks: cloud-functions/tasks/identities.md
    - Marketplace Management Tasks: cloud-functions/tasks/marketplace-management.md
    - Carbon Credit Management Tasks: cloud-functions/tasks/carbon-credit-management.md
    - Trade Deal Tasks: cloud-functions/tasks/trade-deal.md
    - Integration Test Tasks: cloud-functions/tasks/integration-test.md
    - Marketplace Integration Test Tasks: cloud-functions/tasks/integration-test-marketplace.md
    - Trade Deal Integration Test Tasks: cloud-functions/tasks/integration-test-trade-deal.md
    - Admin Utilities: cloud-functions/tasks/admin-utils.md
    - Sync Diamond Tasks: cloud-functions/tasks/sync-diamond.md
    - Sync Events Tasks: cloud-functions/tasks/sync-events.md
  - EIPs (Ethereum Improvement Proposals):
    - Overview: eips/index.md
    - Diamond-Enhanced Marketplace: eips/EIP-DRAFT-Diamond-Enhanced-Marketplace.md
    - Multi-Token Sale Standard: eips/EIP-DRAFT-Multi-Token-Sale-Standard.md
    - Collateralized Trade Deal Standard: eips/EIP-DRAFT-Collateralized-Trade-Deal-Standard.md
    - Enhanced Identity System: eips/EIP-DRAFT-Enhanced-Identity-System.md
    - Diamond Factory Standard: eips/EIP-DRAFT-Diamond-Factory-Standard.md
    - Carbon Credit Standard: eips/EIP-DRAFT-Carbon-Credit-Standard.md
  - Developer Guides:
    - Development Environment Setup: developer-guides/development-environment-setup.md
    - Testing Frameworks: developer-guides/testing-frameworks.md
    - Debugging: developer-guides/debugging.md
    - Performance Optimization: developer-guides/performance-optimization.md
    - Test Case Specifications: developer-guides/test-case-specifications.md
    - Test Data Management: developer-guides/test-data-management.md
    - Automated Testing Setup: developer-guides/automated-testing-setup.md
  - Deployment Guides:
    - Multi-Network Deployment: deployment-guides/multi-network-deployment.md
    - Infrastructure Management: deployment-guides/infrastructure-management.md
    - Monitoring and Logging: deployment-guides/monitoring-logging.md
  - User Guides:
    - Administrator Guide: gemforce-administrator-guide.md
    - Deployer Guide: gemforce-deployer-guide.md
    - Integrator Guide: gemforce-integrator-guide.md
  - Integrator's Guide:
    - Overview: integrator-guide/overview.md
    - Authentication: integrator-guide/authentication.md
    - REST API: integrator-guide/rest-api.md
    - Smart Contracts: integrator-guide/smart-contracts.md
    - DFNS Integration: integrator-guide/dfns.md
    - Parse Server Notes: integrator-guide/parse-server.md
    - Webhooks: integrator-guide/webhooks.md
    - Error Handling: integrator-guide/error-handling.md
    - Sample Code: integrator-guide/sample-code.md
    - Integration Patterns: integrator-guide/integration-patterns.md
    - Testing Considerations: integrator-guide/testing.md
    - Security: integrator-guide/security.md
  - External Services: external-services/gemforce-external-services.md
  - Security:
    - Overview: security/overview.md
    - Threat Model and Risk Assessment: security/threat-model.md
    - Incident Response Procedures: security/incident-response.md
    - Security Audits and Compliance: security/audit-compliance.md
  - External Developer Integration:
    - Overview: external-developer-integration/overview.md
    - API Rate Limiting: external-developer-integration/api-rate-limiting.md
    - Webhook Implementation Guidelines: external-developer-integration/webhook-implementation-guidelines.md
    - SDK Development Guidelines: external-developer-integration/sdk-development-guidelines.md
    - Partner Integration Guides: external-developer-integration/partner-integration-guides.md
  - Documentation Gap Analysis: gemforce-documentation-gap-analysis.md
  - Documentation Progress Summary: documentation-progress-summary.md
  - Documentation Plan: documentation-plan.md
  - Configuration & Environment:
    - Gemforce Config: configuration-environment/gemforce-config.md
    - Environment-Specific Guides: configuration-environment/environment-specific-guides.md
    - Configuration Validation Procedures: configuration-environment/configuration-validation.md
    - External Service Configuration Management: configuration-environment/external-service-config-management.md
    - Database Schema Overview: configuration-environment/database-schema-overview.md
    - Database Migration Procedures: configuration-environment/database-migration-procedures.md

# Theme
theme: readthedocs

# Extensions - using only standard extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - fenced_code
  - attr_list
  - def_list

# Plugins
plugins:
  - search
