site_name: Gemforce Documentation
site_description: Documentation for the Gemforce blockchain platform
site_author: Gemforce Team

# Navigation
nav:
  - Home: index.md
  - Developer Setup Guide: developer-setup-guide.md
  - System Architecture: system-architecture/gemforce-system-architecture.md
  - Smart Contracts:
    - Overview: smart-contracts/index.md
    - Diamond Contract: smart-contracts/diamond.md
    - Facets:
      - Marketplace Facet: smart-contracts/facets/marketplace-facet.md
      - Trade Deal Management Facet: smart-contracts/facets/trade-deal-management-facet.md
      - Carbon Credit Facet: smart-contracts/facets/carbon-credit-facet.md
      - Identity Registry Facet: smart-contracts/facets/identity-registry-facet.md
      - Trusted Issuers Registry Facet: smart-contracts/facets/trusted-issuers-registry-facet.md
      - Fee Distributor Facet: smart-contracts/facets/fee-distributor-facet.md
      - Gemforce Minter Facet: smart-contracts/facets/gemforce-minter-facet.md
      - Multi Sale Facet: smart-contracts/facets/multi-sale-facet.md
      - SVG Templates Facet: smart-contracts/facets/svg-templates-facet.md
      - Trade Deal Admin Facet: smart-contracts/facets/trade-deal-admin-facet.md
      - Trade Deal Operations Facet: smart-contracts/facets/trade-deal-operations-facet.md
      - Collateral Token Factory Facet: smart-contracts/facets/collateral-token-factory-facet.md
    - Interfaces:
      - IDiamond: smart-contracts/interfaces/idiamond.md
      - IMarketplace: smart-contracts/interfaces/imarketplace.md
      - ITradeDeal: smart-contracts/interfaces/itradedeal.md
      - ICarbonCredit: smart-contracts/interfaces/icarbon-credit.md
      - IERC1155Mint: smart-contracts/interfaces/ierc1155-mint.md
      - IERC734: smart-contracts/interfaces/ierc734.md
      - IERC735: smart-contracts/interfaces/ierc735.md
    - Libraries:
      - Carbon Credit Lib: smart-contracts/libraries/carbon-credit-lib.md
      - Trade Deal Lib: smart-contracts/libraries/trade-deal-lib.md
      - Multi Sale Lib: smart-contracts/libraries/multi-sale-lib.md
      - Diamond Factory Lib: smart-contracts/libraries/diamond-factory-lib.md
      - SVG Templates Lib: smart-contracts/libraries/svg-templates-lib.md
      - Attribute Lib: smart-contracts/libraries/attribute-lib.md
      - Variable Price Lib: smart-contracts/libraries/variable-price-lib.md
      - Merkle Prover: smart-contracts/libraries/merkle-prover.md
      - Fee Distributor Lib: smart-contracts/libraries/fee-distributor-lib.md
  - Cloud Functions:
    - Overview: cloud-functions/index.md
    - Blockchain Functions: cloud-functions/blockchain.md
    - DFNS Functions: cloud-functions/dfns.md
    - Contract Functions: cloud-functions/contracts.md
    - Authentication Functions: cloud-functions/authentication.md
  - API Documentation:
    - Full API Reference: api-documentation/gemforce-api-documentation.md
    - Quick Reference: api-documentation/gemforce-api-quick-reference.md
  - EIPs (Ethereum Improvement Proposals):
    - Overview: eips/index.md
    - Diamond-Enhanced Marketplace: eips/EIP-DRAFT-Diamond-Enhanced-Marketplace.md
    - Multi-Token Sale Standard: eips/EIP-DRAFT-Multi-Token-Sale-Standard.md
    - Collateralized Trade Deal Standard: eips/EIP-DRAFT-Collateralized-Trade-Deal-Standard.md
    - Enhanced Identity System: eips/EIP-DRAFT-Enhanced-Identity-System.md
    - Diamond Factory Standard: eips/EIP-DRAFT-Diamond-Factory-Standard.md
    - Carbon Credit Standard: eips/EIP-DRAFT-Carbon-Credit-Standard.md
  - User Guides:
    - Administrator Guide: gemforce-administrator-guide.md
    - Deployer Guide: gemforce-deployer-guide.md
    - Integrator Guide: gemforce-integrator-guide.md
  - External Services: external-services/gemforce-external-services.md
  - Documentation Gap Analysis: gemforce-documentation-gap-analysis.md
  - Documentation Progress Summary: documentation-progress-summary.md
  - Documentation Plan: documentation-plan.md

# Theme
theme: readthedocs

# Extensions - using only standard extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - fenced_code
  - attr_list
  - def_list

# Plugins
plugins:
  - search
