site_name: Gemforce Documentation
site_description: Documentation for the Gemforce blockchain platform
site_author: Gemforce Team

# Navigation
nav:
  - Home: index.md
  - System Architecture: gemforce-system-architecture.md
  - API Documentation:
    - Full API Reference: gemforce-api-documentation.md
    - Quick Reference: gemforce-api-quick-reference.md
  - User Guides:
    - Administrator Guide: gemforce-administrator-guide.md
    - Deployer Guide: gemforce-deployer-guide.md
    - Integrator Guide: gemforce-integrator-guide.md
  - External Services: gemforce-external-services.md
  - Documentation Plan: documentation-plan.md

# Theme
theme: readthedocs

# Extensions - using only standard extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

# Plugins
plugins:
  - search
